[build]
  publish = "target/classes"
  command = "mvn clean package -DskipTests"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  JAVA_VERSION = "17"
  MAVEN_VERSION = "3.9.6"
