server.port=8080

# Session timeout - 5 minutes (300 seconds)
server.servlet.session.timeout=5m
spring.session.timeout=300

spring.thymeleaf.cache=false
spring.web.resources.cache.period=0
spring.web.resources.cache.cachecontrol.no-store=true
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=create-drop